### ISSUE TITLE
User Story for Free DogGo

### ISSUE THREAD

**Issue by MartinK1983** [MartinK1983/Capstone-Project-2023#10]
## Value Proposition

As a User
I want to create profiles about new Spots where dogs can run free
Where I can also add new places with pictures and GPS points
​

## Description
![US 1](https://user-images.githubusercontent.com/121966128/224309560-7a827c4e-b10f-41cb-9fbd-a2cfef41f590.png)

## Acceptance Criteria

- [ ] Error when a criteria (input) isn´t chosen (Please select option)
- [ ] Submit button has to function
- [ ] Inputs need to be saved in local storage
      ​

## Tasks

- [ ]  Create form with inputs options to choose

- [ ] Create submit button

- [ ] Create error message
      ​

**Comment by TuncAlt** [comment]
is this the right wireframe?
