### ISSUE TITLE
Upload your own data

### ISSUE THREAD

**Issue by MartinK1983** [MartinK1983/Capstone-Project-2023#11]
## Value Proposition

As a User
I want to create profiles about new Spots where dogs can run free
Where I can also add new places with pictures and GPS points
​

## Description

![US 2](https://user-images.githubusercontent.com/121966128/224319969-164650d0-90f1-459b-b901-3a633cb6f50f.png)

​

## Acceptance Criteria

- [ ] Click on the field to add images and data
- [ ] Show error field if field is not filled
- [ ] GPS tracking for exact location
      ​

## Tasks

- [ ] Create form with inputs options to choose
- [ ] Create submit button
- [ ] Create error message
      ​
